### ISSUE TITLE
wishlist item: save image

### ISSUE THREAD

**Issue by tidux** [martianhi/mastodon.el#225]
There should be a keybinding or right-click menu option to save an image from a toot, either to a default ($HOME/Downloads) or popping up a save path minibuffer.

**Comment by hdurer** [comment]
With the cursor on the desired image, pressing `o` might work (depends on your Emacs version I believe since we just inherit from `shr-image-map` which in turn inherits from `image-map` if present (and that was only introduced a few versions back I think).

This could be documented better I guess, just like so much...

**Comment by tidux** [comment]
I'm using Spacemacs on Emacs 26 and it just throws a "buffer is read only" error.

**Comment by hdurer** [comment]
Well, I know exactly zero things about Spacemacs, but I just tried it and you are right.  I completely misremembered how things work.  Images aren't even tab stops and don't have a keymap installed either it seems.
