### ISSUE TITLE
Call for contributors

### ISSUE THREAD

**Issue by jdenen** [martianhi/mastodon.el#233]
There's been a pretty decent surge in activity around the project lately, and I'm (quite obviously) unable to keep up. If you're interested in contributing/being a part of a team to maintain this project going forward, let's talk about it in this issue.

**Comment by sabexx** [comment]
Hey @jdenen, if you want help I'm happy to take a look. I'm investigating the "new toot" (#234) issue at the moment.

**Comment by martianhi** [comment]
hi, i recently started using and hacking on mastodon.el. my elisp skills aren't good enough to help maintain your library, but i have added a number of basic functions to my fork:

- jump to my profile
- follow/unfollow, mute/unmute, block/unblock users
- delete existing toots
- a (very basic) search function

i also incorporated the spoiler text into the content warning text, and made the visual separation between toots in the timeline a bit clearer, based on changes made in ieure's fork.

ieure also added some async capabilities, some of which i managed to duplicated for other functions.

would you be interested in looking at/incpororating this? i'm a github novice so am not familiar with the usual process. i've also only tested them through my own use.

**Comment by martianhi** [comment]
hi again, i have since added a few extra things to my fork:

- display of relationship (follows you, followed by you) in profile view
- display pinned toots first
- copy URL of toot at point
- display "fields" (ie profile metadata) in profile view.
- mention booster in replies by default.

my changes are at https://github.com/mooseyboots/mastodon.el.

as mentioned, i'm a noob, so its likely a bit amateur. but some things like profile metadata/pinned toots can also contain important info for users.

any feedback would be welcome.

**Comment by martianhi** [comment]
see #242
