### ISSUE TITLE
migrate to codeberg

### ISSUE THREAD

**Issue by mooseyboots** [martianhi/mastodon.el#243]
if there are no objections, i plan to migrate mastodon.el to codeberg.org.

i did a test migration and it worked fine.

one thing to consider is that magit's `forge` package is currently implementing full support for gitea forges, so it could be a good idea to wait for that.

**Comment by hdurer** [comment]
Will that still have the integration with Travis?  

And Melpa will cope with the move?

**Comment by martianhi** [comment]
@hdurer no travis integration, but it has also been broken a long time and i don't know how to fix it, as i never (successfully) used it.

re: melpa, it's easy to update the recipe to a new location.

i just had a look at codeberg and its easy to set up a mirror, so that's also an easy option.

i don't want to make the repo less available for contributions/issues, but i am in favour of deserting surveillance platforms.

but also, hd if you are not into it, i don't mind holding off.

**Comment by abhiseck** [comment]
> one thing to consider is that magit's forge package is currently implementing full support for gitea forges, so it could be a good idea to wait for that.

I think this is a great opportunity to move this project to Codeberg as development/activity is still low. Once the development picks up it may become harder to move.

**Comment by mooseyboots** [comment]
moved, waiting for MELPA to merge PR to pull from codeberg repo.

**Comment by mooseyboots** [comment]
the migration's done and MELPA updated.

https://codeberg.org/martianh/mastodon.el/
