### ISSUE TITLE
User mention auto-suggestion

### ISSUE THREAD

**Issue by clarkenciel** [martianhi/mastodon.el#90]
It would be nice to get auto-suggestions when mentioning other users in the toot-buffer. Maybe I've missed something, but as far as I can tell users of mastodon.el just have to memorize handles+domains at the moment or open their instance in a browser, which isn't optimal.

This could work like company/ac drop-downs or helm-style buffers.

**Comment by kaushalmodi** [comment]
May be `mastodon.el` can provide a hash-table of all the users I follow. Then using Ivy/Helm, it should be quick to insert those handles.

**Comment by alexjgriffith** [comment]
Doing it strictly based on followers and those following could prove complicated, especially since we can connect through several accounts at the same time.  We could design it so whenever a toot/notification/user is rendered any new handles in the event are added to the hash-table.

Another solution would be to make a search request for users when autocomplete is called on a user handle. 

This should definitely come with a flag, in case users don't want a paper trail of all users and their handles.

**Comment by martianhi** [comment]
is now implemented as company completion. for now it fetches from the server with a prefix query each time with no offline storage. offline storage would be welcome though.
